models/Projects.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "projects".
 *
 * @property int $id
 * @property string|null $user_email
 * @property int|null $project_id
 * @property string|null $delivery_date
 * @property string|null $project_name
 * @property int|null $image_number
 * @property int|null $project_success
 * @property string|null $s3_path
 *
 * @property Users[] $users
 */
class Projects extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'projects';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['project_id', 'image_number', 'project_success'], 'integer'],
            [['user_email', 'project_name'], 'string', 'max' => 64],
            [['delivery_date'], 'string', 'max' => 32],
            [['s3_path'], 'string', 'max' => 128],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'user_email' => 'User Email',
            'project_id' => 'Project ID',
            'delivery_date' => 'Delivery Date',
            'project_name' => 'Project Name',
            'image_number' => 'Image Number',
            'project_success' => 'Project Success',
            's3_path' => 'S 3 Path',
        ];
    }

    /**
     * Gets query for [[Users]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getUsers()
    {
        return $this->hasMany(Users::className(), ['email' => 'user_email']);
    }

    static public function convertToDate($dateTime)
    {
        $time = $dateTime;

        return date("Y-m-d",strtotime($time));
    }

    static public function countPrice($currentUser, $imagesCount)
    {
        $idPlan = $currentUser->id_plan;
        $price = 0;

        switch ($idPlan) {
            case '2':
                $flatRate = 2;
                $maxImages = 200;
                break;
            case '3':
                $flatRate = 3;
                $maxImages = 300;
                break;
            case '4':
                $flatRate = 4;
                $maxImages = 400;
                break;
            default:
                $flatRate = 0;
                $maxImages = 0;
                break;
        }

        if ($imagesCount == $maxImages) {
            $price = $flatRate;
        } elseif ($imagesCount > $maxImages) {
            $price = $flatRate;
            $price += ($imagesCount - $maxImages) * 0.01;

        } elseif ($imagesCount < $maxImages) {
            $price = $imagesCount * $flatRate / $maxImages;
        }

        return $price;
    }
}

models/Users.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "users".
 *
 * @property int $id
 * @property string|null $name
 * @property string|null $company
 * @property string|null $language
 * @property string|null $address
 * @property string|null $country
 * @property string|null $phone
 * @property string|null $email
 * @property int|null $is_verified
 * @property int|null $id_plan
 * @property string|null $city
 * @property int|null $zip_code
 */
class Users extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'users';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['is_verified', 'id_plan', 'zip_code'], 'integer'],
            [['name', 'company', 'city'], 'string', 'max' => 128],
            [['language', 'country', 'email'], 'string', 'max' => 64],
            [['address'], 'string', 'max' => 255],
            [['phone'], 'string', 'max' => 32],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => 'Name',
            'company' => 'Company',
            'language' => 'Language',
            'address' => 'Address',
            'country' => 'Country',
            'phone' => 'Phone',
            'email' => 'Email',
            'is_verified' => 'Is Verified',
            'id_plan' => 'Id Plan',
            'city' => 'City',
            'zip_code' => 'Zip Code',
        ];
    }
}

controllers/SiteController.php
<?php

namespace app\controllers;

use app\models\Projects;
use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\Response;
use yii\filters\VerbFilter;
use app\models\Users;

class SiteController extends Controller
{
    /**
     * Displays user select.
     *
     * @return string
     */
    public function actionIndex()
    {
        $users = Users::find()->all();

        return $this->render('index', ['users' => $users]);
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionViewUser($id)
    {
        var_dump($id);
        $users = Users::find()->all();
        $user = Users::findOne(['id' => $id]);
        $projects = Projects::find()->where(['user_email' => $user->email])->orderBy(['delivery_date' => SORT_DESC])->all();

        return $this->render('view_user', [
            'currentUser' => $user,
            'projects' => $projects,
            'users' => $users
        ]);
    }
}

controllers/XmlParserController.php
<?php

namespace app\controllers;

use app\models\Projects;
use app\models\Users;
use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\Response;
use yii\filters\VerbFilter;
use app\models\LoginForm;
use app\models\ContactForm;

class XmlParserController extends Controller
{
    /**
     * Pars users.
     *
     * @return string
     */
    public function actionParsUsers()
    {
        if (file_exists($_SERVER['DOCUMENT_ROOT'] . '/xml/Users.xml')) {
            $xml = simplexml_load_file($_SERVER['DOCUMENT_ROOT'] . '/xml/Users.xml');
        } else {
            exit('Cant open XML file');
        }

        foreach ($xml->children() as $row) {
            $data_array = (array)$row;

            $id = $data_array['field'][0];
            $name = (string)$data_array['field'][1];
            $company = $data_array['field'][2];
            $language = $data_array['field'][3];
            $address = $data_array['field'][4];
            $country = $data_array['field'][5];
            $phone = $data_array['field'][6];
            $email = $data_array['field'][7];
            $is_verified = (int)$data_array['field'][8];
            $id_plan = $data_array['field'][9];
            $city = $data_array['field'][10];
            $zip_code = (int)$data_array['field'][11];

            $users = new Users();
            $users->id = $id;
            $users->name = $name;
            $users->company = $company;
            $users->language = $language;
            $users->address = $address;
            $users->country = $country;
            $users->phone = $phone;
            $users->email = $email;
            $users->is_verified = $is_verified;
            $users->id_plan = $id_plan;
            $users->city = $city;
            $users->zip_code = $zip_code;
            $users->save(false);
        }

        return $this->render('success');
    }

    /**
     * Pars projects.
     *
     * @return string
     */
    public function actionParsProjects()
    {
        if (file_exists($_SERVER['DOCUMENT_ROOT'] . '/xml/Projects.xml')) {
            $xml = simplexml_load_file($_SERVER['DOCUMENT_ROOT'] . '/xml/Projects.xml');
        } else {
            return $this->render('error');
        }

        foreach ($xml->children() as $row) {
            $data_array = (array)$row;

            $id = $data_array['field'][0];
            $user_email = (string) $data_array['field'][1];
            $project_id = $data_array['field'][2];
            $delivery_date = $data_array['field'][3];
            $project_name = $data_array['field'][4];
            $image_number = (int) $data_array['field'][5];
            $project_success = $data_array['field'][6];
            $s3_path = $data_array['field'][7];

            $projects = new Projects();
            $projects->id = $id;
            $projects->user_email = $user_email;
            $projects->project_id = $project_id;
            $projects->delivery_date = $delivery_date;
            $projects->project_name = $project_name;
            $projects->image_number = $image_number;
            $projects->project_success = $project_success;
            $projects->s3_path = $s3_path;
            $projects->save(false);
        }

        return $this->render('success');
    }
}

views/layouts/main.php
<?php

/** @var yii\web\View $this */
/** @var string $content */

use app\assets\AppAsset;
use app\widgets\Alert;
use yii\bootstrap4\Breadcrumbs;
use yii\bootstrap4\Html;
use yii\bootstrap4\Nav;
use yii\bootstrap4\NavBar;

AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>" class="h-100">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <?php $this->registerCsrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body class="d-flex flex-column h-100">
<?php $this->beginBody() ?>

<header>
    <?php
    NavBar::begin([
        'brandLabel' => Yii::$app->name,
        'brandUrl' => Yii::$app->homeUrl,
        'options' => [
            'class' => 'navbar navbar-expand-md navbar-dark bg-dark fixed-top',
        ],
    ]);
    NavBar::end();
    ?>
</header>

<main role="main" class="flex-shrink-0">
    <div class="container">
        <?= Breadcrumbs::widget([
            'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
        ]) ?>
        <?= Alert::widget() ?>
        <?= $content ?>
    </div>
</main>

<footer class="footer mt-auto py-3 text-muted">
    <div class="container">
        <p class="float-left">&copy; My Company <?= date('Y') ?></p>
        <p class="float-right"><?= Yii::powered() ?></p>
    </div>
</footer>

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>

views/site/error.php
<?php

/** @var yii\web\View $this */
/** @var string $name */
/** @var string $message */
/** @var Exception$exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

views/site/index.php
<?php

use yii\helpers\Url;

/** @var yii\web\View $this */

$this->title = 'My Yii Application';
?>
<div class="site-index">

    <div class="jumbotron text-center bg-transparent">
        <h1 class="display-4">Users page</h1>

        <p>
            <form action="<?= Url::to(['site/view-user']) ?>" method="GET">
                <select onchange="this.form.submit()" name="id">
                    <option>Select user</option>
                    <?php foreach ($users as $user): ?>
                        <option value="<?= $user->id ?>"><?= $user->name ?> (<?= $user->company ?>)</option>
                    <?php endforeach; ?>
                </select>
            </form>
        </p>
    </div>

    <div class="body-content">

        <div class="row">

<!--            <div class="col-lg-4">-->
<!--                <h2>Heading</h2>-->
<!---->
<!--                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et-->
<!--                    dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip-->
<!--                    ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu-->
<!--                    fugiat nulla pariatur.</p>-->
<!---->
<!--                <p><a class="btn btn-outline-secondary" href="http://www.yiiframework.com/doc/">Yii Documentation &raquo;</a></p>-->
<!--            </div>-->
<!--            <div class="col-lg-4">-->
<!--                <h2>Heading</h2>-->
<!---->
<!--                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et-->
<!--                    dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip-->
<!--                    ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu-->
<!--                    fugiat nulla pariatur.</p>-->
<!---->
<!--                <p><a class="btn btn-outline-secondary" href="http://www.yiiframework.com/forum/">Yii Forum &raquo;</a></p>-->
<!--            </div>-->
<!--            <div class="col-lg-4">-->
<!--                <h2>Heading</h2>-->
<!---->
<!--                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et-->
<!--                    dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip-->
<!--                    ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu-->
<!--                    fugiat nulla pariatur.</p>-->
<!---->
<!--                <p><a class="btn btn-outline-secondary" href="http://www.yiiframework.com/extensions/">Yii Extensions &raquo;</a></p>-->
<!--            </div>-->
        </div>

    </div>
</div>

views/site/view_user.php
<?php

use yii\helpers\Url;
use app\models\Projects;
/** @var yii\web\View $this */

$this->title = 'My Yii Application';
?>
<div class="site-index">

    <div class="jumbotron text-center bg-transparent">
        <h1 class="display-4">Users page</h1>

        <p>
            <form action="<?= Url::to(['site/view-user']) ?>" method="GET">
                <select onchange="this.form.submit()" name="id">
                    <option>Select user</option>
                    <?php foreach ($users as $user): ?>
                        <option value="<?= $user->id ?>"><?= $user->name ?> (<?= $user->company ?>)</option>
                    <?php endforeach; ?>
                </select>
            </form>
        </p>
    </div>

    <div class="body-content">

        <div class="row">
<!--            --><?// var_dump($currentUser); ?>
<!--            --><?// var_dump($projects); ?>

            <div class="col-lg-4">
                <h2>User Info</h2>
                <p><strong>Name: </strong><?= $currentUser->name ?></p>
                <p><strong>Company: </strong><?= $currentUser->company ?></p>
                <p><strong>Email: </strong> <?= $currentUser->email ?></p>
                <p><strong>Country: </strong><?= $currentUser->country ?></p>
                <p><strong>Phone: </strong><?= $currentUser->phone ?></p>
                <p><strong>ID_plan: </strong><?= $currentUser->id_plan ?></p>

            </div>
            <div class="col-lg-4">
                <div class="col-sm-12">
                <h2>Projects</h2>
                <table cellpadding="2" border="1">
                    <tr>
                        <td>
                            <p><strong>Date</strong></p>
                        </td>
                        <td>
                            <p><strong>Project name</strong></p>
                        </td>
                        <td>
                            <p><strong>Images</strong></p>
                        </td>
                    </tr>
                    <? $imagesCount = 0 ?>
                    <? $projectDate = 0 ?>
                    <? $price = 0 ?>
                    <?php foreach ($projects as $project): ?>
                        <?
                            if (Projects::convertToDate($projectDate) != Projects::convertToDate($project->delivery_date)) {

                                if ($imagesCount != 0) {
                                    $price += Projects::countPrice($currentUser, $imagesCount);
                                }
                                $imagesCount = 0;
                            }
                            $projectDate = Projects::convertToDate($project->delivery_date);
                            $imagesCount += $project->image_number;

                        ?>
                        <tr>
                            <td>
                                <p><?= Projects::convertToDate($project->delivery_date) ?></p>
                            </td>
                            <td>
                                <p><?= $project->project_name ?></p>
                            </td>
                            <td>
                                <p><?= $project->image_number ?></p>
                            </td>
                        </tr>
                    <?php endforeach; ?>
                    <? $price += Projects::countPrice($currentUser, $imagesCount); ?>
                    </tr>
                </table>
                </div>


            </div>
            <div class="col-lg-4">
                <h2>Total earnings</h2>
                <p><?= $price ?>$</p>
            </div>
        </div>

    </div>
</div>

views/xml-parser/error.php
<div class="site-error">

    <h1>XML parsing result</h1>

    <div class="alert alert-error">
        Error!
    </div>

    <p>
        XML file was not found or there is an error while parsing data.
    </p>
    <p>
        Please, check your XML file.
    </p>

</div>

views/xml-parser/success.php
<div class="site-error">

    <h1>XML parsing result</h1>

    <div class="alert alert-success">
        Success!
    </div>

    <p>
        XML file was successfully parsed.
    </p>
    <p>
        Please, check Data base.
    </p>

</div>